/**
 * Type definitions for AI-Based Test Generation
 */
import { TestCase } from './test-case';
/**
 * Test specification generated by AI from web page analysis
 */
export interface TestSpecification {
    testName: string;
    description: string;
    steps: AIGeneratedStep[];
    tags: string[];
}
/**
 * AI-generated test step before conversion to TestStep format
 */
export interface AIGeneratedStep {
    action: 'navigate' | 'click' | 'type' | 'assert' | 'wait';
    description: string;
    elementDescription?: string;
    value?: string;
    assertion?: {
        type: 'exists' | 'visible' | 'text' | 'value' | 'attribute';
        expected: string;
    };
}
/**
 * Learning context provided to AI Engine for improved generation
 */
export interface LearningContext {
    successfulPatterns: string[];
    failingPatterns: string[];
    selectorPreferences: SelectorStrategy[];
}
/**
 * Options for web page analysis
 */
export interface AnalysisOptions {
    waitForSelector?: string;
    timeout?: number;
    viewport?: {
        width: number;
        height: number;
    };
}
/**
 * Complete analysis results for a web application
 */
export interface ApplicationAnalysis {
    url: string;
    title: string;
    elements: IdentifiedElement[];
    patterns: UIPattern[];
    flows: UserFlow[];
    metadata: PageMetadata;
}
/**
 * Interactive element identified during analysis
 */
export interface IdentifiedElement {
    type: 'button' | 'link' | 'input' | 'select' | 'textarea' | 'checkbox' | 'radio';
    attributes: {
        id?: string;
        class?: string;
        name?: string;
        'aria-label'?: string;
        'data-testid'?: string;
        placeholder?: string;
        text?: string;
    };
    xpath: string;
    cssPath: string;
}
/**
 * UI pattern detected during analysis
 */
export interface UIPattern {
    type: 'form' | 'navigation' | 'modal' | 'table' | 'list';
    elements: IdentifiedElement[];
    description: string;
}
/**
 * User flow identified during analysis
 */
export interface UserFlow {
    name: string;
    steps: string[];
    entryPoint: IdentifiedElement;
}
/**
 * Page metadata captured during analysis
 */
export interface PageMetadata {
    viewport: {
        width: number;
        height: number;
    };
    loadTime: number;
    isSPA: boolean;
}
/**
 * Selector generation strategies in priority order
 */
export type SelectorStrategy = 'data-testid' | 'id' | 'aria-label' | 'name' | 'class' | 'xpath' | 'text-content';
/**
 * Result of test case validation
 */
export interface ValidationResult {
    valid: boolean;
    errors: ValidationError[];
}
/**
 * Validation error details
 */
export interface ValidationError {
    field: string;
    message: string;
}
/**
 * Result of batch test generation
 */
export interface BatchResult {
    successful: TestCase[];
    failed: FailedGeneration[];
    summary: {
        total: number;
        succeeded: number;
        failed: number;
    };
}
/**
 * Failed test generation details
 */
export interface FailedGeneration {
    scenario: string;
    error: string;
}
/**
 * Learning data for a specific domain
 */
export interface LearningData {
    domain: string;
    selectorStats: Map<SelectorStrategy, {
        successes: number;
        failures: number;
    }>;
    failingSelectors: FailedSelector[];
    successfulPatterns: TestPattern[];
    lastUpdated: string;
}
/**
 * Failed selector record
 */
export interface FailedSelector {
    selector: string;
    strategy: SelectorStrategy;
    failureCount: number;
    lastFailure: string;
}
/**
 * Successful test pattern
 */
export interface TestPattern {
    description: string;
    steps: string[];
    successRate: number;
}
/**
 * Learning record stored in DynamoDB
 */
export interface AILearningRecord {
    domain: string;
    recordType: string;
    selectorStrategy?: SelectorStrategy;
    successCount?: number;
    failureCount?: number;
    selector?: string;
    pattern?: TestPattern;
    lastUpdated: string;
}
/**
 * Token usage for an LLM API call
 */
export interface TokenUsage {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
}
/**
 * Usage statistics aggregated by various dimensions
 */
export interface UsageStats {
    totalCalls: number;
    totalTokens: number;
    estimatedCost: number;
    breakdown: {
        byUser: Map<string, number>;
        byProject: Map<string, number>;
        byDate: Map<string, number>;
    };
}
/**
 * AI usage record stored in DynamoDB
 */
export interface AIUsageRecord {
    userId: string;
    timestamp: string;
    projectId: string;
    operationType: 'analyze' | 'generate' | 'batch';
    tokens: TokenUsage;
    cost: number;
    testCasesGenerated: number;
    metadata: {
        model: string;
        duration: number;
    };
}
/**
 * Request to analyze a web application
 */
export interface AnalyzeRequest {
    url: string;
    options?: AnalysisOptions;
}
/**
 * Response from web application analysis
 */
export interface AnalyzeResponse {
    analysis: ApplicationAnalysis;
}
/**
 * Request to generate a single test case
 */
export interface GenerateTestRequest {
    analysis: ApplicationAnalysis;
    scenario: string;
    projectId: string;
    suiteId: string;
}
/**
 * Response from test case generation
 */
export interface GenerateTestResponse {
    testCase: TestCase;
    tokensUsed: TokenUsage;
    cost: number;
}
/**
 * Request to generate multiple test cases
 */
export interface BatchGenerateRequest {
    url: string;
    scenarios: string[];
    projectId: string;
    suiteId: string;
    options?: AnalysisOptions;
}
/**
 * Response from batch test generation
 */
export interface BatchGenerateResponse {
    results: BatchResult;
    tokensUsed: TokenUsage;
    cost: number;
}
/**
 * Query parameters for usage statistics
 */
export interface UsageStatsParams {
    userId?: string;
    projectId?: string;
    startDate?: string;
    endDate?: string;
}
/**
 * Response with usage statistics
 */
export interface UsageStatsResponse {
    stats: UsageStats;
}
/**
 * AI-specific metadata for generated test cases
 */
export interface AITestMetadata {
    generatedAt: string;
    model: string;
    scenario: string;
    analysisUrl: string;
    confidence?: number;
}
/**
 * Extended test case with AI metadata
 */
export interface AIGeneratedTestCase extends TestCase {
    aiGenerated: boolean;
    aiMetadata: AITestMetadata;
}
